version: '2'

services:
  jenkins:
    build: master
    restart: always
    volumes:
       - ./jenkins_home:/var/jenkins_home
    ports:
      - "80:8080"
      - "50000:50000"
    links:
      - slave
    environment:
      - JAVA_OPTS=-Xmx512m

  slave:
    build: slave
    restart: always
